### ISSUE TITLE
環境整備

### ISSUE THREAD

**Issue by goosys** [goosys/misty-bird-7370#1]
# Tasks

- [x] gemを初期化 https://github.com/goosys/misty-bird-7370/commit/9881006e858039ebf7c7f124c0067b42f054394d
  - `bundle gem administrate-mistybird -t` 
- [x] gemspecの設定 https://github.com/goosys/misty-bird-7370/commit/9f7066924cddf275114c44a7b834e7a9c9607f38
- [x] Gemfile.lockをgit管理から外す https://github.com/goosys/misty-bird-7370/commit/b17f3a0d832eb3f72ad42f2bd113057660e84bb9 https://github.com/goosys/misty-bird-7370/commit/62b29cad47604b04ae1cb72395a407c8ef1cb3cb
- [x] 生成された不要なテストを削除 https://github.com/goosys/misty-bird-7370/commit/30d540a42a104f87b423262b956e1f15404e86eb
- [x] テスト実行用のRailsアプリケーションを作成 https://github.com/goosys/misty-bird-7370/commit/faa98004bf505804bb95464aa0c7395e3c31f638
  - `rails new example_app -T --skip-docker --skip-keeps -C --skip-bootsnap --database=sqlite3`
  - [x] いくつかskipしたことでassetsが利用不可になっていたので修正 https://github.com/goosys/misty-bird-7370/commit/51d81bbaca4f497b4a7c017142517d91103a0231#diff-a442b5294ccf37b4241fd0dc8c41447e83a876352115d1cfd4be9501c8973d01
- [x] rspecを設定 https://github.com/goosys/misty-bird-7370/commit/51d81bbaca4f497b4a7c017142517d91103a0231 https://github.com/goosys/misty-bird-7370/commit/62fabaad016cad9915811085e5a35f76e8f5db3a
  - [x] `with_translations` をAdministrateからコピー https://github.com/goosys/misty-bird-7370/commit/51d81bbaca4f497b4a7c017142517d91103a0231#diff-64d08b392e52c7b8ff60db12de9a750e01ba252ff5bd00f616d3fe5805ad1e7e
  - [x] `RSpec` ネームスペース無しで `describe` 等が使えるように https://github.com/goosys/misty-bird-7370/commit/51d81bbaca4f497b4a7c017142517d91103a0231#diff-89eebfcbc0f14b6d989517837ca1e94fce4e2ce9a03233641cd936f2b8d2ed94
