### ISSUE TITLE
Field::Refileを実装

### ISSUE THREAD

**Issue by goosys** [goosys/misty-bird-7370#3]
# Issues

- 配布されているField::Refileはメンテされていない
- 削除に対応していないため追加したい
- アップロードしたファイルが表示されるようにしたい
  - 画像ならサムネイルでプレビューしたい
  - 画像（SVG）はリサイズにかけるとエラーになるため、style属性でサムネイル化したい
  - 画像以外はファイルへのリンクを表示したい

# Tasks

- [x] Field::Refileから必要なファイルをコピー https://github.com/goosys/misty-bird-7370/commit/6bb5127f1768aebcd185346fd808d14c5a598ecb
- [x] require https://github.com/goosys/misty-bird-7370/commit/e51ced27738b9a85df21102b64fe03ca58558392
- [x] 削除用のpermitted_attributeを追加 https://github.com/goosys/misty-bird-7370/commit/d05a6bf9358ad93c2adb06a15f4b8d944fb6fe94
- [x] 削除用のチェックボックスを追加 https://github.com/goosys/misty-bird-7370/commit/d05a6bf9358ad93c2adb06a15f4b8d944fb6fe94
- [x] アップロードしたファイルが表示されるように修正 https://github.com/goosys/misty-bird-7370/commit/d05a6bf9358ad93c2adb06a15f4b8d944fb6fe94
- [x] spec
  - [x] pendingで追加 https://github.com/goosys/misty-bird-7370/commit/25c34e46e94c5448d668557de400ece5695040ab

# Todos

- Refileは１attrで複数アップロードに対応しているが、そこまでは対応できていない
  - ※Arrayだった場合の分岐は入れているが未検証
- フォームでファイルを選択した時点でプレビューを出したい
- 削除用のボタンがかっこ悪い
- specを実装
