### ISSUE TITLE
RoleAwareResourceResolverを実装

### ISSUE THREAD

**Issue by goosys** [goosys/misty-bird-7370#4]
# Issues

- `/provider` `/manager` `/admin` など複数ネームスペースでそれぞれの管理画面を作りたい

# Tasks

- [x] ResourceResolverをAdministrateからコピー https://github.com/goosys/misty-bird-7370/commit/b750ece78f539ea821cb5d02f2bc4a1343d5987e
- [x] RoleAwareResourceResolverを実装 https://github.com/goosys/misty-bird-7370/commit/bc221242f3a2979790b5fb106e4202ca941979bd
- [x] `Administrate::Page::Base#resource_name` からネームスペース部分を取り除くように修正
- [x] `Administrate::BaseDashboard#model` からもネームスペース部分を取り除くように修正
- [x] rspec

# Todos

- 多段のネームスペースには未対応 https://github.com/goosys/misty-bird-7370/commit/bc221242f3a2979790b5fb106e4202ca941979bd#diff-1b794be08a353a7998c3eacd7009bdce99007d0103ef0c0ae39c9c80495a5920R15
  - モデルのネームスペースなのか権限分けのためのネームスペースなのか区別できないため
